FORMAT: 1A
HOST: http://api.dicastanha.com.br/

# Dicastanha API

This API provide management information from system integrated with photos that Dicastanha provide.

## Authorization [/v1/auth/login]

### Login [POST]

+ Request (application/json)

        {   
            "_username": "email@partner.com",
            "_password": "p4ssw0rd"
        }

+ Response 200 (application/json)

        {
           "success": true,
           "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJuYW1lIjoibXBzYW50b3NAbG9wZXMuY29tLmJyYSIsImV4cCI6MTQ4NzQzOTQ3OX0.pmPbQAIZVaTbQpTx0-FdBldxPlQCeZirb1qdhrbvddQ"
        }

+ Response 400 (application/json)

        {
            "success": false,
            "error": "Invalid credentials"
        }

### Create a New Question [GET]

You may create your own question using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ Request (application/json)

        {
            "question": "Favourite programming language?",
            "choices": [
                "Swift",
                "Python",
                "Objective-C",
                "Ruby"
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }