FORMAT: 1A
HOST: http://api.dicastanha.com.br/

# Dicastanha API

This API provide management information from system integrated with photos that Dicastanha provide.

## Authorization [/v1/auth/login]

### Login [POST]

+ Request (application/json)

        {   
            "_username": "email@partner.com",
            "_password": "p4ssw0rd"
        }

+ Response 200 (application/json)

        {
           "success": true,
           "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJuYW1lIjoibXBzYW50b3NAbG9wZXMuY29tLmJyYSIsImV4cCI6MTQ4NzQzOTQ3OX0.pmPbQAIZVaTbQpTx0-FdBldxPlQCeZirb1qdhrbvddQ"
        }

+ Response 400 (application/json)

        {
            "success": false,
            "error": "Invalid credentials"
        }